bluealpha_pipeline:
  outputs:
    dev:
      dbname: local
      host: localhost
      pass: password
      port: 5433
      schema: dbt_martinchen
      threads: 1
      type: postgres
      user: postgres
  target: dev
