dbt_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DB_HOST', 'postgres') }}"
      port: 5432
      user: "{{ env_var('DB_USER', 'postgres') }}"
      password: "{{ env_var('DB_PASSWORD', 'password') }}"
      dbname: "{{ env_var('DB_NAME', 'postgres') }}"
      schema: dbt_output
      threads: 1